### PR TITLE
DefaultSerializationBinder Update

### PR DESCRIPTION
**Pull request by TylerBrinkley**
Addresses #926 and #949

### CODE REVIEW

**Comment by JamesNK** [comment]
This is really great. I made a couple of changes but it was very close to what I wanted to do.

**Comment by TylerBrinkley** [comment]
Glad I could help. I'm just glad I can ditch my CustomSerializationBinder after the next release.

**Comment by cremor** [comment]
@JamesNK Any chance to get a release that includes this fix soon? It's been 9 months since the last release and previously new releases happend more frequently.

**Comment by JamesNK** [comment]
About 2 weeks

**Pull request merged**
