### PR TITLE
Optimized decimal parsing

### PR DESCRIPTION
**Pull request by TylerBrinkley**
Avoids string allocation

### CODE REVIEW

**Comment by TylerBrinkley** [comment]
Not sure why AppVeyor didn't run after the second commit.

**Comment by TylerBrinkley** [comment]
Using [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) these are the average times I got deserializing a list of 5000 `decimal`s.

```
x64
  old: 1.8630 ms
  new: 1.2445 ms

x86
  old: 1.7826 ms
  new: 1.3850 ms
```

**Comment by TylerBrinkley** [comment]
@JamesNK Just seeing if you've been able to look over this. It should be the last piece needed to fulfill #772.

**Comment by JamesNK** [comment]
Yeah I'll get to it before 10r1. I've been focusing on Roslyn project stuff lately.

**Comment by JamesNK** [comment]
I looked over it and the logic and tests look ok. I did a performance test and it was about the same speed to a little slower than the default decimal.TryParse. Any ideas for performance improvements?

**Comment by TylerBrinkley** [comment]
I just further optimized the parsing performance. I believe that's the best I can get it.

**Comment by JamesNK** [comment]
I did some more testing, this time with BenchmarkDotNet and yours was faster - I'm not sure whether it was your recent changes or my previous test wasn't that great.

Thanks a lot. Merged!

**Pull request merged**
