### PR TITLE
fix issue with JSONPath query expression when compare string with a number

### PR DESCRIPTION
**Pull request by MinhNguyenDev**
To fix issue #1379

### CODE REVIEW

**Comment by JamesNK** [comment]
A problem I see is your change will break the comparison in the opposite direction.

This test will fail after the PR:

```
        [Test]
        public void GreaterThan_ComparingStringParameterWithIntegerValues()
        {
            string json = @"{
  ""persons"": [
    {
      ""name""  : ""John"",
      ""age"": 26
    },
    {
      ""name""  : ""Jane"",
      ""age"": 2
    }
  ]
}";

            JObject models = JObject.Parse(json);

            var results = models.SelectTokens("$.persons[?(@.age > '3')]").ToList();

            Assert.AreEqual(1, results.Count);
        }

```

**Comment by MinhNguyenDev** [comment]
Thanks for your reply, James! But in pratice the right hand value is the one we have control, we can choose > 3 or > '3', the left hand is the field in JSON object that we can't change. So I think this can be a quick work around to support most use cases.

**Comment by JamesNK** [comment]
I don't like quick fixes. The proper fix is to make `leftValue.CompareTo(rightValue)` and `rightValue.CompareTo(leftValue)` return equivalent results.

**Comment by JamesNK** [comment]
I made this change instead - https://github.com/JamesNK/Newtonsoft.Json/commit/ad1a13728a2f155d6b4f2ca39bcac4b9873e344a

**Pull request closed without merging**
