### PR TITLE
Customize type attribute

### PR DESCRIPTION
**Pull request by jpassing**
The Json.Net library, when using a setting other than ```TypeNamingHandling.None```, emits and interprets ```$type```properties to support polymorphism. The name ```$type``` is hardcoded.

This PR adds the capability for clients to customize the name of the  ```$type``` property, which allows them to leverage the existing polymorphism-mechanisms for consuming REST APIs that also rely on polymorphism, yet use disscriminating properties named other than ```$type``` (such as ```_type```).

### CODE REVIEW

**Comment by GaTechThomas** [comment]
Will this change be added to release version? If so, what expected time frame?

**Comment by antwilliams** [comment]
Has there been any discussion about this being integrated in to the main branch?
We are currently maintaining an internal build of the JSON library to get this feature, we need it to maintain compatibility with types serialised by a third party who use ServiceStack.Text.

**Comment by jpassing** [comment]
No, I have not gotten any feedback or indications about this being merged at all.

**Comment by JamesNK** [comment]
I don't want to add this. I have to draw the line at customization at some point and I don't want all the various property names changeable. If I do it for type then people will ask for it for $ref, $id, $value, etc.

**Comment by tinyg** [comment]
Hi James,

I dont suppose we can open the conversation on this again? We have to parse GeoJSON on a regular basis and this one improvement would make that a piece of cake - without it I have to basically rewrite the whole document replacing "type" with "$type" before I can use Json.NET to serialize it.

I completely understand re opening a can of worms on customizing all the properties but the type property seems like a special case as so many "standard" json formats have custom "type" properties which cant be serialized by Json.NET.

Cheers,
Chris

**Comment by BalassaMarton** [comment]
Making the `$ref`, `$id`, etc. properties customizable would totally make sense and would fit into place with JSON.NET's other customization features. Maybe introduce a `IMetadataTokenProvider' interface into the serializer settings?

**Comment by avranju** [comment]
The reason why being able to customize the attribute name on which the serializer predicates type selection is useful is in cases where the expectation is that other JSON processing software that aren't based on this library will interact with your application. Think of a web API that consumes JSON produced by clients that aren't .NET based. In this case, expecting those clients to produce JSON with an attribute named `$type` just to accommodate the choice of JSON serialization software on the server is likely to be unacceptable.

**Pull request closed without merging**
