### PR TITLE
Property names can now be renamed

### PR DESCRIPTION
**Pull request by abibell**
Property names can now be renamed using .Rename("newPropertyName") to resolve https://github.com/JamesNK/Newtonsoft.Json/issues/548
- Added unit tests to cover the functionality

### CODE REVIEW

**Comment by JamesNK** [comment]
Sorry I don't like this. It doesn't make sense when the value is inside an array for example.

**Comment by abibell** [comment]
So we can do it for non array objects. Any data should support CRUD
operations don't you think? At the moment we don't do update. It's a valid
feature from user point of view.

**Comment by abibell** [comment]
Anyone who wishes to use this functionality can use the code below:
```c#
public static class NewtonsoftExtensions
{
    public static void Rename(this JToken token, string newName)
    {
        var parent = token.Parent;
        if (parent == null)
            throw new InvalidOperationException("The parent is missing.");
        var newToken = new JProperty(newName, token);
        parent.Replace(newToken);
    }
```

**Comment by mikkoviitala** [comment]
:+1:

**Comment by Maxime66410** [comment]
> 

IDK why i follow the problem #548 and i use your solution, but i get always _"Accessed JObject values with invalid key value: 0. Object property name expected."_

**Pull request closed without merging**
