### PR TITLE
DefaultReferenceResolver Concurrency Fix

### LINKED ISSUE #870: Concurrency issue in DefaultReferenceResolver/JsonSerializer
Just saw the exception below with JsonSerializer being used in a multi-threaded environment, which I believe is due to the _referenceCount++ in DefaultReferenceResolver.GetReference() not being thread-safe (should be using Interlocked.Increment).
Also the internal dictionaries in BiDirectionalDictionary are not thread-safe either, and there's no synchronization mechanism around them.

System.ArgumentException: A different value already has the Id '181186'.
   at Newtonsoft.Json.Utilities.BidirectionalDictionary`2.Set(TFirst first, TSecond second)
   at Newtonsoft.Json.Serialization.DefaultReferenceResolver.GetReference(Object context, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetReference(JsonWriter writer, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetReference(JsonWriter writer, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReferenceIdProperty(JsonWriter writer, Type type, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteObjectStart(JsonWriter writer, Object value, JsonContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)

### PR DESCRIPTION
**Pull request by TylerBrinkley**
In case you won't accept #1393 this is the easy fix to some of the concurrency issues.

Fixes #870 and #1452

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Any update on this? Ran into this issue in https://github.com/akkadotnet/akka.net/pull/5197

**Comment by JamesNK** [comment]
This type isn't designed to have thread-safety.

Even if the id was incremented with Interlocked, the underlying collections aren't thread-safe. And if the collections were made threadsafe then performance would probably take a big hit because all serialization shares the same collections and there will be a ton of lock contention.

**Comment by TylerBrinkley** [comment]
It seems the underlying `BidirectionalDictionary` is specific to the serialization context and thus does not need to be thread safe as it should only be accessed from a single thread whereas the `DefaultReferenceResolver` itself is shared across serialization calls thus users have experienced these concurrency issues.

You yourself said `JsonSerializer` is thread-safe at https://stackoverflow.com/questions/36186276/is-the-json-net-jsonserializer-threadsafe so it seems the intent would be for the `DefaultReferenceResolver` to be thread-safe also since it's used by `JsonSerializer` but that's not true when using references as indicated in my answer to that question. This small change should fix the concurrency issue but I still think this type should either avoid being stateful by pushing the reference count into the context or else creating a new `ReferenceResolver` for each serialization call as is proposed in #1393.

**Comment by Aaronontheweb** [comment]
Yeah the idea that the serializer itself isn't / can't be thread-safe seems crazy to me. Move the state to the context or the call, not the callsite itself.

**Comment by TylerBrinkley** [comment]
Closing due to age.

**Pull request closed without merging**
