### PR TITLE
Deserialization of a concurrent dictionary with null value (fix for issue #1582)

### PR DESCRIPTION
**Pull request by testfirstcoder**

### CODE REVIEW

**Comment by testfirstcoder** [comment]
Issue [1582](https://github.com/JamesNK/Newtonsoft.Json/issues/1582)

**Comment by JamesNK** [comment]
Hmmm, the problem I have with this is now every dictionary will call contains before setting the value which hurts performance. Also some user implementations of dictionary might not have implemented Contains or Add, and would start throwing errors.

Why does `ConcurrentDictionary` error when using the index setter with null? IMO it looks like a bug with `ConcurrentDictionary`

**Comment by testfirstcoder** [comment]
@JamesNK Added an issue [26447](https://github.com/dotnet/corefx/issues/26447) to [dotnet/corefx](https://github.com/dotnet/corefx).

**Comment by JamesNK** [comment]
Worked around with https://github.com/JamesNK/Newtonsoft.Json/commit/8ece2b31b90c479572c70713c8e72f3ed48684d5

**Pull request closed without merging**
