### PR TITLE
Add support for DateOnly and TimeOnly

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/JamesNK/Newtonsoft.Json/issues/2521

### CODE REVIEW

**Comment by VinzSpring** [comment]
When will this be released in the nuget package? We kinda need this asap... 🚀

**Comment by JamesNK** [comment]
5 days ago

**Comment by Gnimuc** [comment]
Hi @JamesNK, thank for fixing this! Would you mind releasing a new version so we don't need to patch this manually in our project?

**Comment by JamesNK** [comment]
It’s on nuget

**Comment by Gnimuc** [comment]
We are using the pre-released version 13.0.2-beta1 and it works well, but we're not allowed to use a beta lib in our products. :)

**Comment by JamesNK** [comment]
You’ll need to build your apartment an version then

**Comment by nesc58** [comment]
Is the next release already scheduled?

**Comment by sjd2021** [comment]
This is working great for me @JamesNK. Thank you! 
I am running into some conflicts with using other packages like NSwag that aren't targeting any beta versions. Do you know when the next major release will be so that we could revisit using any packages that might have these problems?

**Comment by goldenc** [comment]
@JamesNK what about adding support for `DateOnly` and `TimeOnly` in JValue ?

**Pull request merged**
