### PR TITLE
Added string conversion virtual methods to JsonConverter

### PR DESCRIPTION
**Pull request by TylerBrinkley**
Added string conversion virtual methods to JsonConverter to support dictionary key serialization and deserialization which addresses #915.

Fixed merge conflict from previous PR #1035.

### CODE REVIEW

**Comment by fgreinacher** [comment]
I like this a lot!

**Comment by TylerBrinkley** [comment]
Fixed merge conflict related to the change to compilation constants by feature.

**Comment by JamesNK** [comment]
I've been considering this for a while and I think it puts too much on JsonConverter. I would prefer to stick with TypeConverter as the way for converting strings in dictionary types. I just recently added support for the netstandard1.0 build for TypeConverter so it is available everywhere, and I want to invest a little more in support for specifying a TypeConverter via a contract resolver, and caching it to improve the performance.

**Comment by TylerBrinkley** [comment]
Maybe it does put too much on `JsonConverter` but it does make things more intuitive. One would expect if using the `StringEnumConverter` that the dictionary key would be serialized the same as a value would without having to recreate the same logic with the same settings in a `TypeConverter` class. And currently for primitive types a `TypeConverter` is not even looked for during serialization or deserialization so as an example enums are serialized with a [call](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs#L1169) to `Convert.ToString`.

**Pull request closed without merging**
