### PR TITLE
ISerializable support for NetStandard 1.3

### PR DESCRIPTION
**Pull request by skarllot**
I've made some changes for ISerializable usage on NetStandard 1.3.

The build script ran successfully: [runbuild.txt](https://github.com/JamesNK/Newtonsoft.Json/files/650511/runbuild.txt)

### CODE REVIEW

**Comment by skarllot** [comment]
Tests updated for NetStandard 1.3

The build script ran successfully: [runbuild.txt](https://github.com/JamesNK/Newtonsoft.Json/files/650551/runbuild.txt)

**Comment by skarllot** [comment]
Latest build script output: [runbuild.txt](https://github.com/JamesNK/Newtonsoft.Json/files/655802/runbuild.txt)

**Comment by skarllot** [comment]
I've flatten commits and rebased to latest upstream commits.

**Comment by skarllot** [comment]
@JamesNK I need to improve something to get this PR merged?

**Comment by skarllot** [comment]
I've rebased and reviewed latest changes for NetStandard 1.3 support.

**Comment by JamesNK** [comment]
I want to wait until after VS2017 is out and move from project.json to csproj before adding new builds.

**Comment by skarllot** [comment]
I've rebased and fixed some compiler conditions.

@JamesNK The build script is ready and testings are passing. I don't know any other impediment.
This change will not affect future migration to 2017 csproj.

**Comment by skarllot** [comment]
@JamesNK That is your final answer? If so, this pull can be closed.

**Pull request closed without merging**
